spring.datasource.url=${DATASOURCE_URL}
spring.datasource.hikari.username=${DATASOURCE_USERNAME}
spring.datasource.hikari.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}

server.port=5000

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}