spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
spring.datasource.hikari.username=${RDS_USERNAME}
spring.datasource.hikari.password=${RDS_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}

server.port=5000